(()=>{"use strict";
const sb=window.supabase.createClient(window.FRSHOP_SUPABASE_URL,window.FRSHOP_SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});
const ADMIN="manseurange@gmail.com",$=s=>document.querySelector(s);let products=[],payments=[],orders=[],store={};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function showApp(){const loginView=$("#loginView"),appView=$("#appView");loginView.hidden=true;loginView.style.display="none";appView.hidden=false;appView.style.display="block";document.body.classList.add("admin-active");load().catch(e=>console.error("Dashboard load:",e))}
async function boot(){try{const {data,error}=await sb.auth.getSession();if(error)throw error;if(data.session?.user?.email?.toLowerCase()===ADMIN)showApp();else if(data.session)await sb.auth.signOut()}catch(e){console.error("Session error:",e)}}
async function login(email,password){
  const timeout=new Promise((_,reject)=>setTimeout(()=>reject(new Error("La connexion à Supabase a pris trop de temps. Vérifiez votre connexion Internet puis réessayez.")),15000));
  const result=await Promise.race([sb.auth.signInWithPassword({email,password}),timeout]);
  if(result.error)throw result.error;
  return result.data;
}
$("#loginForm").onsubmit=async e=>{
 e.preventDefault();
 const status=$("#loginStatus"),button=$("#loginForm button");
 const email=$("#adminEmail").value.trim().toLowerCase(),password=$("#adminPass").value;
 status.textContent="Connexion…";button.disabled=true;
 try{
   if(email!==ADMIN){status.textContent="Compte non autorisé.";return}
   const data=await login(email,password);
   if(data.user?.email?.toLowerCase()!==ADMIN){await sb.auth.signOut();status.textContent="Compte non autorisé.";return}
   status.textContent="Connexion réussie…";showApp();
 }catch(error){console.error("Admin login:",error);status.textContent=error?.message||"Échec de connexion."}
 finally{button.disabled=false}
};
$("#logout").onclick=async()=>{await sb.auth.signOut();location.reload()};
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>go(b.dataset.section));
document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));
function go(id){document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.section===id));document.querySelectorAll(".view").forEach(x=>x.hidden=x.id!==id);const titles={overview:"Vue générale",products:"Produits",payments:"Paiements",orders:"Commandes",settings:"Paramètres du site"};$("#pageTitle").textContent=titles[id]||"Dashboard"}
async function load(){const [p,m,o,s]=await Promise.all([sb.from("products").select("*").order("created_at",{ascending:false}),sb.from("payment_methods").select("*").order("id"),sb.from("orders").select("*").order("created_at",{ascending:false}),sb.from("site_settings").select("value").eq("key","store").maybeSingle()]);if(p.error||m.error||o.error||s.error){console.error(p.error,m.error,o.error,s.error);return}products=p.data||[];payments=m.data||[];orders=o.data||[];store=s.data?.value||{};$("#statProducts").textContent=products.length;$("#statPayments").textContent=payments.filter(x=>x.enabled).length;$("#statOrders").textContent=orders.length;$("#statRevenue").textContent=orders.reduce((a,o)=>a+Number(o.total||0),0).toFixed(2)+" USDT";renderProducts();renderPayments();renderOrders();renderSettings();$("#recentOrders").innerHTML=orders.length?orders.slice(0,6).map(orderRow).join(""):"<p class='empty'>Aucune commande.</p>";bindOrders()}
function orderRow(o){return '<div class="row"><b>'+esc(o.id)+'</b><small>'+esc(o.customer?.name||"Client")+'</small><span>'+Number(o.total||0).toFixed(2)+' USDT</span><button class="mini" data-order="'+esc(o.id)+'">Voir</button></div>'}
function renderProducts(){$("#productGrid").innerHTML='<div class="row"><b>Produit</b><b>Catégorie</b><b>Prix</b><b>Actions</b></div>'+(products.length?products.map(p=>'<div class="row"><b>'+esc(p.name)+'</b><small>'+esc(p.category)+'</small><span>'+Number(p.price).toFixed(2)+' USDT</span><div class="actions"><button data-edit="'+esc(p.id)+'">Modifier</button><button data-del="'+esc(p.id)+'">Supprimer</button></div></div>').join(""):"<p class='empty'>Aucun produit.</p>");document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>editProduct(b.dataset.edit));document.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>deleteProduct(b.dataset.del))}
function renderPayments(){$("#paymentGrid").innerHTML=payments.length?payments.map(p=>'<div class="wallet"><h3>'+esc(p.name)+'</h3><small>'+esc(p.network)+' · '+(p.enabled?"Actif":"Désactivé")+'</small><p>'+esc(p.wallet_address||p.url||"")+'</p>'+(p.qr_url?'<p><a target="_blank" rel="noopener" href="'+esc(p.qr_url)+'">QR code ↗</a></p>':"")+'<div class="actions"><button data-pe="'+p.id+'">Modifier</button><button data-pd="'+p.id+'">Supprimer</button></div></div>').join(""):"<p class='empty'>Aucun moyen de paiement.</p>";document.querySelectorAll("[data-pe]").forEach(b=>b.onclick=()=>editPayment(b.dataset.pe));document.querySelectorAll("[data-pd]").forEach(b=>b.onclick=()=>deletePayment(b.dataset.pd))}
function renderOrders(){const q=($("#orderSearch").value||"").toLowerCase();const list=orders.filter(o=>(o.id+" "+(o.customer?.name||"")+" "+(o.customer?.email||"")).toLowerCase().includes(q));$("#ordersTable").innerHTML=list.length?list.map(orderRow).join(""):"<p class='empty'>Aucune commande trouvée.</p>";bindOrders()}
function bindOrders(){document.querySelectorAll("[data-order]").forEach(b=>b.onclick=()=>showOrder(b.dataset.order))}
$("#orderSearch").oninput=renderOrders;document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>b.closest(".modal").classList.remove("open"));
function openModal(id){$(id).classList.add("open")}
function editProduct(id){const p=products.find(x=>x.id===id);if(!p)return;$("#productForm").reset();$("#pid").value=p.id;$("#pname").value=p.name;$("#pcat").value=p.category;$("#pprice").value=p.price;$("#purl").value=p.payment_url||"";$("#pfeatured").checked=!!p.featured;$("#imagePreview").innerHTML=(Array.isArray(p.images)?p.images:[]).map(x=>'<img class="thumb" src="'+esc(x)+'">').join("");openModal("#productModal")}
$("#newProduct").onclick=()=>{$("#productForm").reset();$("#pid").value="";$("#imagePreview").innerHTML="";openModal("#productModal")};
$("#productForm").onsubmit=async e=>{e.preventDefault();const id=$("#pid").value||"p-"+Date.now(),old=products.find(x=>x.id===id),images=Array.isArray(old?.images)?[...old.images]:[];for(const f of $("#pimagesFile").files){if(f.size>10*1024*1024)continue;const path=id+"/"+Date.now()+"-"+f.name.replace(/[^a-zA-Z0-9._-]/g,"_");const up=await sb.storage.from("product-images").upload(path,f,{contentType:f.type,upsert:false});if(up.error){alert(up.error.message);return}images.push(sb.storage.from("product-images").getPublicUrl(path).data.publicUrl)}const data={id,name:$("#pname").value.trim(),category:$("#pcat").value.trim(),price:Number($("#pprice").value),payment_url:$("#purl").value.trim()||null,featured:$("#pfeatured").checked,images,updated_at:new Date().toISOString()};const r=old?await sb.from("products").update(data).eq("id",id):await sb.from("products").insert(data);if(r.error){alert(r.error.message);return}$("#productModal").classList.remove("open");await load()};
async function deleteProduct(id){if(!confirm("Supprimer ce produit ?"))return;const r=await sb.from("products").delete().eq("id",id);if(r.error)alert(r.error.message);else await load()}
function editPayment(id){const p=payments.find(x=>String(x.id)===String(id));if(!p)return;$("#paymentForm").reset();$("#payId").value=p.id;$("#payName").value=p.name;$("#payNetwork").value=p.network;$("#payWallet").value=p.wallet_address||"";$("#payQr").value=p.qr_url||"";$("#payUrl").value=p.url||"";$("#payEnabled").checked=!!p.enabled;openModal("#paymentModal")}
$("#newPayment").onclick=()=>{$("#paymentForm").reset();$("#payId").value="";$("#payEnabled").checked=true;openModal("#paymentModal")};
$("#paymentForm").onsubmit=async e=>{e.preventDefault();const id=$("#payId").value,data={name:$("#payName").value.trim(),network:$("#payNetwork").value.trim(),wallet_address:$("#payWallet").value.trim()||null,qr_url:$("#payQr").value.trim()||null,url:$("#payUrl").value.trim()||null,enabled:$("#payEnabled").checked};const r=id?await sb.from("payment_methods").update(data).eq("id",id):await sb.from("payment_methods").insert(data);if(r.error){alert(r.error.message);return}$("#paymentModal").classList.remove("open");await load()};
async function deletePayment(id){if(!confirm("Supprimer ce moyen de paiement ?"))return;const r=await sb.from("payment_methods").delete().eq("id",id);if(r.error)alert(r.error.message);else await load()}
function renderSettings(){const s=store;$("#sName").value=s.name||"";$("#sHeroTitle").value=s.hero_title||"";$("#sHeroEmphasis").value=s.hero_emphasis||"";$("#sHeroText").value=s.hero_text||"";$("#sBanner").value=s.banner_url||"";$("#sDeliveryText").value=s.delivery_text||"";$("#sDeliveryPrice").value=s.delivery_price||"";$("#sDeliveryLabel").value=s.delivery_label||""}
$("#settingsForm").onsubmit=async e=>{e.preventDefault();const value={...store,name:$("#sName").value.trim(),hero_title:$("#sHeroTitle").value.trim(),hero_emphasis:$("#sHeroEmphasis").value.trim(),hero_text:$("#sHeroText").value.trim(),banner_url:$("#sBanner").value.trim(),delivery_text:$("#sDeliveryText").value.trim(),delivery_price:$("#sDeliveryPrice").value.trim(),delivery_label:$("#sDeliveryLabel").value.trim(),currency:"USDT"};const r=await sb.from("site_settings").upsert({key:"store",value,updated_at:new Date().toISOString()},{onConflict:"key"});if(r.error){$("#settingsStatus").textContent=r.error.message;return}store=value;$("#settingsStatus").textContent="✓ Paramètres enregistrés";setTimeout(()=>$("#settingsStatus").textContent="",2000)}
function showOrder(id){const o=orders.find(x=>x.id===id);if(!o)return;const c=o.customer||{},items=Array.isArray(o.items)?o.items:[];$("#orderDetails").innerHTML='<div class="order-detail"><p><b>'+esc(o.id)+'</b></p><p>'+esc(c.name)+'<br>'+esc(c.email)+'<br>'+esc(c.phone)+'<br>'+esc(c.address)+', '+esc(c.postal)+' '+esc(c.city)+'<br>'+esc(c.department)+'</p><p>Paiement : '+esc(o.payment)+'</p><div>'+items.map(i=>'<div class="row"><span>'+esc(i.name)+'</span><span>'+Number(i.price||0).toFixed(2)+' USDT</span></div>').join("")+'</div><h3>Total : '+Number(o.total||0).toFixed(2)+' USDT</h3>'+(o.payment_screenshot_path?'<a target="_blank" rel="noopener" href="'+esc(o.payment_screenshot_path)+'">Voir la preuve de paiement ↗</a>':"")+'</div>';openModal("#orderModal")}
boot();
})();