const supabase=window.supabase.createClient(window.FRSHOP_SUPABASE_URL,window.FRSHOP_SUPABASE_KEY);
let products=[],payments=[],orders=[],selectedProductImages=[],editingPaymentId=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
const money=v=>Number(v||0).toLocaleString("fr-FR",{minimumFractionDigits:2,maximumFractionDigits:2})+" USDT";
function toast(m,e=false){const x=$("#toast");x.textContent=m;x.className="toast show"+(e?" error":"");clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.className="toast",3000)}
function status(m,e=true){const x=$("#loginStatus");x.textContent=m;x.style.color=e?"#d92d3f":"#149447"}
function openDrawer(id){$("#"+id).classList.add("show")}function closeDrawer(id){$("#"+id).classList.remove("show")}
function imageOf(p){return p.images?.[0]||"data:image/svg+xml;charset=UTF-8,"+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="500" height="400"><rect width="100%" height="100%" fill="#eef0f3"/><text x="50%" y="50%" text-anchor="middle" dominant-baseline="middle" fill="#8b919a" font-size="24">FR SHOP</text></svg>')}
async function login(e){e.preventDefault();const b=$("#loginButton");b.disabled=true;b.textContent="Connexion...";status("");try{const email=$("#adminEmail").value.trim().toLowerCase(),password=$("#adminPass").value;if(!email||!password)throw Error("Veuillez remplir les deux champs.");const r=await supabase.auth.signInWithPassword({email,password});if(r.error)throw r.error;if(!r.data.user||r.data.user.email.toLowerCase()!=="manseurange@gmail.com"){await supabase.auth.signOut();throw Error("Accès administrateur refusé.");}$("#loginView").classList.add("hidden");$("#appView").classList.remove("hidden");await loadAll();status("Connexion réussie.",false)}catch(e){status(e.message||"Connexion impossible.")}finally{b.disabled=false;b.textContent="Ouvrir l’administration"}}
async function loadAll(){const [a,b,c]=await Promise.all([supabase.from("products").select("*").order("created_at",{ascending:false}),supabase.from("payment_methods").select("*").order("created_at",{ascending:false}),supabase.from("orders").select("*").order("created_at",{ascending:false})]);if(a.error)throw a.error;if(b.error)throw b.error;if(c.error)throw c.error;products=(a.data||[]).map(p=>({...p,images:Array.isArray(p.images)?p.images:[]}));payments=b.data||[];orders=c.data||[];render()}
function render(){stats();recent();popular();categories();productList();paymentList();orderList()}
function stats(){$("#statProducts").textContent=products.length;$("#statPayments").textContent=payments.filter(p=>p.enabled).length;$("#statOrders").textContent=orders.length;$("#statRevenue").textContent=money(orders.reduce((n,o)=>n+Number(o.total||0),0))}
function recent(){const x=$("#recentOrders");x.innerHTML=orders.length?orders.slice(0,5).map(o=>{const c=o.customer||{};return '<div class="order-mini"><div><b>'+esc(o.id)+'</b><small>'+new Date(o.created_at).toLocaleString("fr-FR")+'</small></div><div><b>'+esc(c.name||"Client")+'</b><small>'+esc(c.email||"")+'</small></div><b>'+money(o.total)+'</b><button class="text-btn" onclick="showOrder(\''+esc(o.id)+'\')">Voir</button></div>'}).join(""):'<div class="empty">Aucune commande.</div>'}
function popular(){$("#popularProducts").innerHTML=products.slice(0,5).map(p=>'<div class="mini-product"><img src="'+esc(imageOf(p))+'"><div><b>'+esc(p.name)+'</b><small>'+money(p.price)+'</small></div></div>').join("")||'<div class="empty">Aucun produit.</div>'}
function categories(){const s=$("#productCategory"),v=s.value,c=[...new Set(products.map(p=>p.category).filter(Boolean))].sort();s.innerHTML='<option value="">Toutes les catégories</option>'+c.map(x=>'<option value="'+esc(x)+'">'+esc(x)+'</option>').join("");s.value=v}
function productList(){const q=$("#productSearch").value.toLowerCase(),c=$("#productCategory").value,l=products.filter(p=>(!q||(p.name+" "+p.category).toLowerCase().includes(q))&&(!c||p.category===c));$("#productGrid").innerHTML=l.length?'<div class="product-head"><span>PRODUIT</span><span>CATÉGORIE</span><span>PRIX</span><span>STATUT</span><span></span></div>'+l.map(p=>'<div class="product-row"><div class="prod-name"><img src="'+esc(imageOf(p))+'"><div><b>'+esc(p.name)+'</b><small>'+esc(p.payment_url?"Binance Pay configuré":"Aucun lien Binance")+'</small></div></div><span>'+esc(p.category)+'</span><span class="price">'+money(p.price)+'</span><span class="pill '+(p.featured?"green":"")+'">'+(p.featured?"Mis en avant":"Standard")+'</span><div class="row-actions"><button class="icon-btn" onclick="editProduct(\''+esc(p.id)+'\')">Modifier</button><button class="icon-btn danger" onclick="deleteProduct(\''+esc(p.id)+'\')">×</button></div></div>').join(""):'<div class="empty">Aucun produit trouvé.</div>'}
function paymentList(){$("#paymentGrid").innerHTML=payments.length?payments.map(p=>'<article class="wallet-card"><div class="wallet-head"><div class="wallet-title"><span class="coin">₿</span><div><h3>'+esc(p.name)+'</h3><small>'+esc(p.network||"Réseau")+'</small></div></div><span class="pill '+(p.enabled?"green":"")+'">'+(p.enabled?"Actif":"Désactivé")+'</span></div>'+(p.wallet_address?'<div class="wallet-address">'+esc(p.wallet_address)+'</div>':"")+(p.qr_url?'<img src="'+esc(p.qr_url)+'" alt="QR">':"")+'<div class="wallet-actions"><button class="btn secondary" onclick="editPayment('+p.id+')">Modifier</button><button class="btn secondary" onclick="deletePayment('+p.id+')">Supprimer</button></div></article>').join(""):'<div class="empty">Aucun moyen de paiement.</div>'}
function orderList(){const q=$("#orderSearch").value.toLowerCase(),l=orders.filter(o=>{const c=o.customer||{};return !q||(o.id+" "+(c.name||"")+" "+(c.email||"")).toLowerCase().includes(q)});$("#ordersTable").innerHTML=l.length?'<div class="order-head"><span>COMMANDE</span><span>CLIENT</span><span>TOTAL</span><span>PREUVE</span><span></span></div>'+l.map(o=>{const c=o.customer||{};return '<div class="order-row"><div><b>'+esc(o.id)+'</b><small>'+new Date(o.created_at).toLocaleString("fr-FR")+'</small></div><div><b>'+esc(c.name||"Client")+'</b><small>'+esc(c.email||"")+'</small></div><b>'+money(o.total)+'</b><span class="pill '+(o.payment_screenshot_path?"green":"")+'">'+(o.payment_screenshot_path?"Preuve reçue":"Sans preuve")+'</span><button class="btn secondary" onclick="showOrder(\''+esc(o.id)+'\')">Détails</button></div>'}).join(""):'<div class="empty">Aucune commande.</div>'}
function preview(){const f=[...$("#pimagesFile").files];$("#imagePreview").innerHTML=selectedProductImages.map((u,i)=>'<div class="thumb"><img src="'+esc(u)+'"><button type="button" onclick="removeImage('+i+')">×</button></div>').join("")+f.map(x=>'<div class="thumb"><img src="'+URL.createObjectURL(x)+'"></div>').join("")}
window.removeImage=i=>{selectedProductImages.splice(i,1);preview()};
async function uploadImages(id){const fs=[...$("#pimagesFile").files];if(fs.length>3)throw Error("Maximum 3 images.");const u=[];for(const f of fs){if(!["image/png","image/jpeg","image/webp"].includes(f.type))throw Error("Format image non accepté.");if(f.size>10485760)throw Error("Image maximum 10 Mo.");const ext=(f.name.split(".").pop()||"jpg").replace(/[^a-z0-9]/gi,"");const path=id+"/"+crypto.randomUUID()+"."+ext,r=await supabase.storage.from("product-images").upload(path,f,{contentType:f.type});if(r.error)throw r.error;u.push(supabase.storage.from("product-images").getPublicUrl(path).data.publicUrl)}return [...selectedProductImages,...u].slice(0,3)}
function newProduct(){selectedProductImages=[];$("#productForm").reset();$("#pid").value="";$("#productModalTitle").textContent="Nouveau produit";$("#imagePreview").innerHTML="";openDrawer("productModal")}
function editProduct(id){const p=products.find(x=>x.id===id);if(!p)return;$("#productForm").reset();$("#pid").value=p.id;$("#pname").value=p.name||"";$("#pcat").value=p.category||"";$("#pprice").value=p.price||0;$("#purl").value=p.payment_url||"";$("#pfeatured").checked=!!p.featured;selectedProductImages=[...(p.images||[])];preview();$("#productModalTitle").textContent="Modifier le produit";openDrawer("productModal")}
async function saveProduct(e){e.preventDefault();try{const id=$("#pid").value||"p-"+Date.now(),images=await uploadImages(id),data={id,name:$("#pname").value.trim(),category:$("#pcat").value.trim(),price:Number($("#pprice").value),images,payment_url:$("#purl").value.trim(),featured:$("#pfeatured").checked,updated_at:new Date().toISOString()};const r=$("#pid").value?await supabase.from("products").update(data).eq("id",id):await supabase.from("products").insert(data);if(r.error)throw r.error;closeDrawer("productModal");await loadAll();toast("Produit enregistré.")}catch(e){toast(e.message||"Erreur",true)}}
async function deleteProduct(id){if(!confirm("Supprimer ce produit ?"))return;const r=await supabase.from("products").delete().eq("id",id);if(r.error){toast(r.error.message,true);return}await loadAll();toast("Produit supprimé.")}
function newPayment(){editingPaymentId=null;$("#paymentForm").reset();$("#payEnabled").checked=true;$("#paymentModalTitle").textContent="Nouveau réseau";openDrawer("paymentModal")}
function editPayment(id){const p=payments.find(x=>x.id===id);if(!p)return;editingPaymentId=id;$("#payName").value=p.name||"";$("#payNetwork").value=p.network||"";$("#payWallet").value=p.wallet_address||"";$("#payQr").value=p.qr_url||"";$("#payUrl").value=p.url||"";$("#payEnabled").checked=!!p.enabled;$("#paymentModalTitle").textContent="Modifier le réseau";openDrawer("paymentModal")}
async function savePayment(e){e.preventDefault();try{const d={name:$("#payName").value.trim(),network:$("#payNetwork").value.trim(),wallet_address:$("#payWallet").value.trim(),qr_url:$("#payQr").value.trim(),url:$("#payUrl").value.trim(),enabled:$("#payEnabled").checked};const r=editingPaymentId?await supabase.from("payment_methods").update(d).eq("id",editingPaymentId):await supabase.from("payment_methods").insert(d);if(r.error)throw r.error;closeDrawer("paymentModal");await loadAll();toast("Paiement enregistré.")}catch(e){toast(e.message||"Erreur",true)}}
async function deletePayment(id){if(!confirm("Supprimer ce moyen de paiement ?"))return;const r=await supabase.from("payment_methods").delete().eq("id",id);if(r.error){toast(r.error.message,true);return}await loadAll();toast("Moyen supprimé.")}
function showOrder(id){const o=orders.find(x=>x.id===id);if(!o)return;const c=o.customer||{};$("#orderDetails").innerHTML='<span class="tag">COMMANDE</span><h2 class="detail-title">'+esc(o.id)+'</h2><div class="detail-grid"><div class="detail-box"><small>Client</small><b>'+esc(c.name||"—")+'</b></div><div class="detail-box"><small>Total</small><b>'+money(o.total)+'</b></div><div class="detail-box"><small>E-mail</small><b>'+esc(c.email||"—")+'</b></div><div class="detail-box"><small>Téléphone</small><b>'+esc(c.phone||"—")+'</b></div><div class="detail-box"><small>Adresse</small><b>'+esc(c.address||"—")+'</b></div><div class="detail-box"><small>Ville / département</small><b>'+esc((c.city||"—")+" / "+(c.department||"—"))+'</b></div></div><h3>Paiement</h3><div class="detail-box">'+esc(o.payment||"—")+'</div>'+(o.payment_screenshot_path?'<h3>Preuve de paiement</h3><img class="proof" src="'+esc(o.payment_screenshot_path)+'">':"");openDrawer("orderModal")}
async function logout(){await supabase.auth.signOut();$("#appView").classList.add("hidden");$("#loginView").classList.remove("hidden")}
$$(".tab").forEach(b=>b.onclick=()=>{$$(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$$(".view").forEach(v=>v.classList.remove("active"));$("#"+b.dataset.section).classList.add("active")});
$$("[data-go]").forEach(b=>b.onclick=()=>{const t=b.dataset.go;$$(".tab").forEach(x=>x.classList.toggle("active",x.dataset.section===t));$$(".view").forEach(v=>v.classList.toggle("active",v.id===t))});
$$("[data-close]").forEach(b=>b.onclick=()=>closeDrawer(b.dataset.close));
$("#loginForm").addEventListener("submit",login);$("#logout").onclick=logout;$("#newProduct").onclick=newProduct;$("#quickProduct").onclick=newProduct;$("#productForm").addEventListener("submit",saveProduct);$("#pimagesFile").addEventListener("change",preview);$("#newPayment").onclick=newPayment;$("#paymentForm").addEventListener("submit",savePayment);$("#productSearch").addEventListener("input",productList);$("#productCategory").addEventListener("change",productList);$("#orderSearch").addEventListener("input",orderList);$("#refreshOrders").onclick=async()=>{await loadAll();toast("Commandes actualisées.")};
(async()=>{try{const s=await supabase.auth.getSession();if(s.data.session&&s.data.session.user?.email?.toLowerCase()==="manseurange@gmail.com"){await loadAll();$("#loginView").classList.add("hidden");$("#appView").classList.remove("hidden")}}catch(e){console.error(e)}})();