const supabase=window.supabase.createClient(window.FRSHOP_SUPABASE_URL,window.FRSHOP_SUPABASE_KEY);
const defaultProducts=[
{id:"p1",name:"Smartphone Pro X",category:"Téléphones",price:399,images:["https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80"],paymentUrl:"#",featured:true},
{id:"p2",name:"Ordinateur Portable Air",category:"Ordinateurs",price:699,images:["https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80"],paymentUrl:"#",featured:true},
{id:"p3",name:"Smartwatch Active",category:"Montres",price:129,images:["https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=900&q=80"],paymentUrl:"#",featured:true},
{id:"p4",name:"Casque Bluetooth Pro",category:"Audio",price:89,images:["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80"],paymentUrl:"#"},
{id:"p5",name:"Clavier Mécanique RGB",category:"Accessoires PC",price:59,images:["https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80"],paymentUrl:"#"},
{id:"p6",name:"Souris Gaming Ultra",category:"Gaming",price:39,images:["https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=900&q=80"],paymentUrl:"#"}
];
const regions=["01 Ain","02 Aisne","03 Allier","04 Alpes-de-Haute-Provence","05 Hautes-Alpes","06 Alpes-Maritimes","07 Ardèche","08 Ardennes","09 Ariège","10 Aube","11 Aude","12 Aveyron","13 Bouches-du-Rhône","14 Calvados","15 Cantal","16 Charente","17 Charente-Maritime","18 Cher","19 Corrèze","2A Corse-du-Sud","2B Haute-Corse","21 Côte-d’Or","22 Côtes-d’Armor","23 Creuse","24 Dordogne","25 Doubs","26 Drôme","27 Eure","28 Eure-et-Loir","29 Finistère","30 Gard","31 Haute-Garonne","32 Gers","33 Gironde","34 Hérault","35 Ille-et-Vilaine","36 Indre","37 Indre-et-Loire","38 Isère","39 Jura","40 Landes","41 Loir-et-Cher","42 Loire","43 Haute-Loire","44 Loire-Atlantique","45 Loiret","46 Lot","47 Lot-et-Garonne","48 Lozère","49 Maine-et-Loire","50 Manche","51 Marne","52 Haute-Marne","53 Mayenne","54 Meurthe-et-Moselle","55 Meuse","56 Morbihan","57 Moselle","58 Nièvre","59 Nord","60 Oise","61 Orne","62 Pas-de-Calais","63 Puy-de-Dôme","64 Pyrénées-Atlantiques","65 Hautes-Pyrénées","66 Pyrénées-Orientales","67 Bas-Rhin","68 Haut-Rhin","69 Rhône","70 Haute-Saône","71 Saône-et-Loire","72 Sarthe","73 Savoie","74 Haute-Savoie","75 Paris","76 Seine-Maritime","77 Seine-et-Marne","78 Yvelines","79 Deux-Sèvres","80 Somme","81 Tarn","82 Tarn-et-Garonne","83 Var","84 Vaucluse","85 Vendée","86 Vienne","87 Haute-Vienne","88 Vosges","89 Yonne","90 Territoire de Belfort","91 Essonne","92 Hauts-de-Seine","93 Seine-Saint-Denis","94 Val-de-Marne","95 Val-d’Oise","971 Guadeloupe","972 Martinique","973 Guyane","974 La Réunion","976 Mayotte"];
let products=[];
let payments=[];
let cart=JSON.parse(localStorage.getItem("frshop_cart")||"[]");
const $=s=>document.querySelector(s);
async function loadStore(){const a=await supabase.from("products").select("*").order("created_at");const b=await supabase.from("payment_methods").select("*").eq("enabled",true).order("created_at");products=a.data?.length?a.data.map(p=>({...p,p.paymentUrl:p.payment_url||"#",images:Array.isArray(p.images)?p.images:[]})):defaultProducts;payments=b.data||[];renderProducts();renderCart()}
function renderProducts(){let q=$("#searchInput").value.toLowerCase(),cat=window.activeCat||"",sort=$("#sort").value;let list=products.filter(p=>(!q||p.name.toLowerCase().includes(q)||p.category.toLowerCase().includes(q))&&(!cat||p.category===cat));if(sort==="priceAsc")list.sort((a,b)=>a.price-b.price);if(sort==="priceDesc")list.sort((a,b)=>b.price-a.price);$("#products").innerHTML=list.map(p=>'<article class="product"><div class="product-img"><img src="'+(p.images?.[0]||"https://placehold.co/600x600?text=Produit")+'" alt="'+p.name+'"><span class="tag">'+p.category+'</span></div><div class="product-body"><div class="cat">FR SHOP</div><h3>'+p.name+'</h3><div class="price">'+Number(p.price).toFixed(2)+' USDT</div><button class="buy" onclick="addToCart(\''+p.id+'\')">Ajouter au panier</button></div></article>').join("");$("#empty").classList.toggle("hidden",!list.length)}
function addToCart(id){let p=products.find(x=>x.id===id);if(!p)return;let x=cart.find(x=>x.id===id);x?x.qty++:cart.push({id,qty:1});saveCart();openCart()}
function saveCart(){localStorage.setItem("frshop_cart",JSON.stringify(cart));renderCart()}
function renderCart(){let total=0;$("#cartItems").innerHTML=cart.map(i=>{let p=products.find(x=>x.id===i.id);if(!p)return"";total+=p.price*i.qty;return '<div class="cart-row"><img src="'+(p.images?.[0]||"https://placehold.co/100")+'"><div><h4>'+p.name+'</h4><div>'+p.price.toFixed(2)+' USDT</div><div class="qty"><button onclick="changeQty(\''+p.id+'\',-1)">−</button>'+i.qty+'<button onclick="changeQty(\''+p.id+'\',1)">+</button></div></div><strong>'+(p.price*i.qty).toFixed(2)+'</strong></div>'}).join("")||'<p class="muted">Votre panier est vide.</p>';$("#cartTotal").textContent=total.toFixed(2)+" USDT";$("#cartCount").textContent=cart.reduce((s,x)=>s+x.qty,0)}
function changeQty(id,d){let x=cart.find(x=>x.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(x=>x.id!==id);saveCart()}
function openCart(){$("#drawer").classList.add("open");$("#overlay").classList.add("show")}function closeCart(){$("#drawer").classList.remove("open");$("#overlay").classList.remove("show")}
function openCheckout(){if(!cart.length)return alert("Votre panier est vide.");$("#regionSelect").innerHTML='<option value="">Sélectionnez votre département</option>'+regions.map(r=>'<option>'+r+'</option>').join("");$("#paymentChoices").innerHTML=payments.filter(p=>p.enabled!==false).map((p,i)=>'<label class="payment"><input required type="radio" name="payment" value="'+i+'"><div><strong>'+p.name+'</strong><div class="muted">'+(p.network||"")+'</div></div></label>').join("")||'<div class="payment">Les moyens de paiement seront bientôt disponibles.</div>';$("#checkoutModal").classList.add("show");closeCart()}
$("#searchInput").addEventListener("input",renderProducts);$("#sort").addEventListener("change",renderProducts);$("#cartBtn").onclick=openCart;$("#closeCart").onclick=closeCart;$("#overlay").onclick=closeCart;$("#checkoutBtn").onclick=openCheckout;$("#closeModal").onclick=()=>$("#checkoutModal").classList.remove("show");document.querySelectorAll(".categories button").forEach(b=>b.onclick=()=>{window.activeCat=b.dataset.cat;renderProducts();location.hash="products"});
$("#orderForm").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),idx=Number(f.get("payment")),pay=payments.filter(p=>p.enabled!==false)[idx],total=cart.reduce((s,i)=>{let p=products.find(x=>x.id===i.id);return s+p.price*i.qty},0);let file=$("#paymentScreenshot").files[0];if(!file){alert("Veuillez importer la capture d’écran du paiement.");return;}if(file.size>10*1024*1024){alert("La capture d’écran doit faire moins de 10 Mo.");return;}if(pay?.url&&pay.url!=="#")window.open(pay.url,"_blank");else alert("Commande enregistrée. Le lien de paiement sera fourni par le vendeur.");let orders=JSON.parse(localStorage.getItem("frshop_orders")||"[]");let reader=new FileReader();reader.onload=()=>{orders.push({id:"ORD-"+Date.now(),customer:Object.fromEntries(f.entries()),items:cart,total,payment:pay?.name||"",createdAt:new Date().toISOString(),paymentScreenshot:reader.result});localStorage.setItem("frshop_orders",JSON.stringify(orders));cart=[];saveCart();$("#checkoutModal").classList.remove("show");e.target.reset();$("#screenshotPreview").innerHTML=""};reader.readAsDataURL(file)};
loadStore();
$("#paymentScreenshot").addEventListener("change",e=>{const f=e.target.files[0];$("#screenshotPreview").innerHTML=f?'<img src="'+URL.createObjectURL(f)+'" alt="Aperçu de la preuve de paiement">':""});
