(() => {
"use strict";
const sb=window.supabase.createClient(window.FRSHOP_SUPABASE_URL,window.FRSHOP_SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s); let products=[],payments=[],cart=[];
const deps=["01 Ain","02 Aisne","03 Allier","04 Alpes-de-Haute-Provence","05 Hautes-Alpes","06 Alpes-Maritimes","07 Ardèche","08 Ardennes","09 Ariège","10 Aube","11 Aude","12 Aveyron","13 Bouches-du-Rhône","14 Calvados","15 Cantal","16 Charente","17 Charente-Maritime","18 Cher","19 Corrèze","2A Corse-du-Sud","2B Haute-Corse","21 Côte-d'Or","22 Côtes-d'Armor","23 Creuse","24 Dordogne","25 Doubs","26 Drôme","27 Eure","28 Eure-et-Loir","29 Finistère","30 Gard","31 Haute-Garonne","32 Gers","33 Gironde","34 Hérault","35 Ille-et-Vilaine","36 Indre","37 Indre-et-Loire","38 Isère","39 Jura","40 Landes","41 Loir-et-Cher","42 Loire","43 Haute-Loire","44 Loire-Atlantique","45 Loiret","46 Lot","47 Lot-et-Garonne","48 Lozère","49 Maine-et-Loire","50 Manche","51 Marne","52 Haute-Marne","53 Mayenne","54 Meurthe-et-Moselle","55 Meuse","56 Morbihan","57 Moselle","58 Nièvre","59 Nord","60 Oise","61 Orne","62 Pas-de-Calais","63 Puy-de-Dôme","64 Pyrénées-Atlantiques","65 Hautes-Pyrénées","66 Pyrénées-Orientales","67 Bas-Rhin","68 Haut-Rhin","69 Rhône","70 Haute-Saône","71 Saône-et-Loire","72 Sarthe","73 Savoie","74 Haute-Savoie","75 Paris","76 Seine-Maritime","77 Seine-et-Marne","78 Yvelines","79 Deux-Sèvres","80 Somme","81 Tarn","82 Tarn-et-Garonne","83 Var","84 Vaucluse","85 Vendée","86 Vienne","87 Haute-Vienne","88 Vosges","89 Yonne","90 Territoire de Belfort","91 Essonne","92 Hauts-de-Seine","93 Seine-Saint-Denis","94 Val-de-Marne","95 Val-d'Oise","971 Guadeloupe","972 Martinique","973 Guyane","974 La Réunion","976 Mayotte"];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const money=v=>Number(v||0).toLocaleString("fr-FR",{minimumFractionDigits:2,maximumFractionDigits:2})+" USDT";
const img=p=>Array.isArray(p.images)&&p.images[0]?p.images[0]:"https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=900&q=80";
function status(msg){const x=$("#checkoutStatus");if(x)x.textContent=msg}
async function load(){
 const [pr,pm]=await Promise.all([sb.from("products").select("*").order("featured",{ascending:false}).order("created_at",{ascending:false}),sb.from("payment_methods").select("*").eq("enabled",true).order("id")]);
 if(pr.error){console.error(pr.error); $("#productsGrid").innerHTML='<div class="error">Impossible de charger les produits.</div>';return}
 products=pr.data||[]; payments=pm.data||[]; buildCategories(); render(); renderPayments(); buildForms();
}
function buildCategories(){const cats=[...new Set(products.map(p=>p.category).filter(Boolean))];$("#categoryList").innerHTML='<button class="cat active-cat" data-cat="">✦<b>Tous les produits</b><small>Afficher tout</small></button>'+cats.map(c=>'<button class="cat" data-cat="'+esc(c)+'">✦<b>'+esc(c)+'</b><small>Découvrir</small></button>').join("");document.querySelectorAll(".cat").forEach(b=>b.onclick=()=>{document.querySelectorAll(".cat").forEach(x=>x.classList.remove("active-cat"));b.classList.add("active-cat");render(b.dataset.cat||"")})}
function render(filter=""){const q=($("#search")?.value||"").trim().toLowerCase();const list=products.filter(p=>(!filter||p.category===filter)&&((p.name||"")+" "+(p.category||"")).toLowerCase().includes(q));$("#productsGrid").innerHTML=list.length?list.map(p=>'<article class="product"><img loading="lazy" src="'+esc(img(p))+'" alt="'+esc(p.name)+'" onerror="this.src=\'https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=900&q=80\'"><div class="body"><small>'+esc(p.category)+'</small><h3>'+esc(p.name)+'</h3><div class="foot"><b>'+money(p.price)+'</b><button class="add" data-id="'+esc(p.id)+'">Ajouter</button></div>'+(p.payment_url?'<a class="product-pay" target="_blank" rel="noopener" href="'+esc(p.payment_url)+'">Paiement direct ↗</a>':"")+'</div></article>').join(""):'<div class="empty">Aucun produit trouvé.</div>';document.querySelectorAll(".add").forEach(b=>b.onclick=()=>{const p=products.find(x=>x.id===b.dataset.id);if(p){cart.push(p);updateCart();$("#cartDrawer").classList.add("open")}})}
function renderPayments(){$("#paymentGrid").innerHTML=payments.length?payments.map(p=>'<div class="payment"><b>'+esc(p.name)+'</b><small>'+esc(p.network||"Crypto")+'</small><div class="wallet">'+esc(p.wallet_address||"Paiement via lien")+'</div>'+(p.url?'<a class="product-pay" target="_blank" rel="noopener" href="'+esc(p.url)+'">Ouvrir le paiement ↗</a>':"")+'</div>').join(""):'<div class="empty">Aucun moyen de paiement disponible.</div>'}
function updateCart(){$("#cartCount").textContent=cart.length;$("#cartItems").innerHTML=cart.length?cart.map((p,i)=>'<div class="cartline"><img src="'+esc(img(p))+'" alt=""><div><b>'+esc(p.name)+'</b><br><span>'+money(p.price)+'</span></div><button class="remove" data-i="'+i+'">×</button></div>').join(""):"<p class='empty'>Votre panier est vide.</p>";$("#cartTotal").textContent=money(cart.reduce((s,p)=>s+Number(p.price||0),0));document.querySelectorAll(".remove").forEach(b=>b.onclick=()=>{cart.splice(Number(b.dataset.i),1);updateCart()})}
function buildForms(){$("#department").innerHTML='<option value="">Département</option>'+deps.map(d=>'<option value="'+esc(d)+'">'+esc(d)+'</option>').join("");$("#paymentMethod").innerHTML='<option value="">Méthode de paiement</option>'+payments.map(p=>'<option value="'+esc(p.name+" — "+p.network)+'">'+esc(p.name+" — "+p.network)+'</option>').join("")}
async function checkout(e){e.preventDefault();if(!cart.length)return status("Votre panier est vide.");const f=$("#paymentScreenshot").files[0];if(!f)return status("Veuillez joindre la preuve de paiement.");if(!["image/png","image/jpeg","image/webp"].includes(f.type))return status("Format accepté : PNG, JPG ou WEBP.");if(f.size>10*1024*1024)return status("La capture doit faire 10 MB maximum.");status("Envoi de la commande…");const id="FR-"+Date.now().toString(36).toUpperCase(),safe=f.name.replace(/[^a-zA-Z0-9._-]/g,"_"),path=id+"/"+safe;const up=await sb.storage.from("payment-screenshots").upload(path,f,{contentType:f.type,upsert:false});if(up.error){console.error(up.error);return status("Erreur d'envoi de la preuve : "+up.error.message)}const publicUrl=sb.storage.from("payment-screenshots").getPublicUrl(path).data.publicUrl;const customer={name:$("#customerName").value.trim(),email:$("#customerEmail").value.trim(),phone:$("#customerPhone").value.trim(),address:$("#customerAddress").value.trim(),city:$("#customerCity").value.trim(),postal:$("#customerPostal").value.trim(),department:$("#department").value};const total=cart.reduce((s,p)=>s+Number(p.price||0),0);const r=await sb.from("orders").insert({id,customer,items:cart.map(p=>({id:p.id,name:p.name,price:p.price})),total,payment:$("#paymentMethod").value,payment_screenshot_path:publicUrl});if(r.error){console.error(r.error);return status("Erreur lors de la commande : "+r.error.message)}status("✓ Commande "+id+" envoyée avec succès.");cart=[];updateCart();setTimeout(()=>$("#checkoutModal").classList.remove("open"),1800)}
document.addEventListener("DOMContentLoaded",()=>{ $("#search").oninput=()=>render(document.querySelector(".active-cat")?.dataset.cat||"");$("#cartBtn").onclick=()=>$("#cartDrawer").classList.add("open");document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>b.closest(".drawer,.modal").classList.remove("open"));$("#checkoutBtn").onclick=()=>{if(!cart.length)return alert("Votre panier est vide.");$("#cartDrawer").classList.remove("open");$("#checkoutModal").classList.add("open")};$("#checkoutForm").onsubmit=checkout;load();});
})();